// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"crmgo/internal/models"
	"time"
)

type AuthResult struct {
	Token         string       `json:"token"`
	User          *models.User `json:"user"`
	SetupRequired *bool        `json:"setupRequired,omitempty"`
	NextStep      *string      `json:"nextStep,omitempty"`
}

type CreateContactInput struct {
	Name           string  `json:"name"`
	Email          *string `json:"email,omitempty"`
	Phone          *string `json:"phone,omitempty"`
	OrganisationID *string `json:"organisationId,omitempty"`
}

type CreateDealInput struct {
	Name        string   `json:"name"`
	PropertyID  string   `json:"propertyId"`
	AssignedTo  *string  `json:"assignedTo,omitempty"`
	Status      *string  `json:"status,omitempty"`
	Value       *float64 `json:"value,omitempty"`
	InitialNote *string  `json:"initialNote,omitempty"`
}

type CreateDiscussionInput struct {
	DealID   string `json:"dealId"`
	Comments string `json:"comments"`
}

type CreateDocumentInput struct {
	Title      string  `json:"title"`
	FileURL    string  `json:"fileUrl"`
	FileType   *string `json:"fileType,omitempty"`
	DealID     *string `json:"dealId,omitempty"`
	PropertyID *string `json:"propertyId,omitempty"`
}

type CreateMeetingInput struct {
	DealID      string    `json:"dealId"`
	Datetime    time.Time `json:"datetime"`
	Title       *string   `json:"title,omitempty"`
	Description *string   `json:"description,omitempty"`
	Location    *string   `json:"location,omitempty"`
}

type CreateOrganisationInput struct {
	OrganisationName string `json:"organisationName"`
}

type CreatePropertyInput struct {
	Name           string  `json:"name"`
	Address        *string `json:"address,omitempty"`
	OwnerID        *string `json:"ownerId,omitempty"`
	Status         *string `json:"status,omitempty"`
	OrganisationID *string `json:"organisationId,omitempty"`
}

type CreateTaskInput struct {
	Title       string     `json:"title"`
	Description *string    `json:"description,omitempty"`
	DueDate     *time.Time `json:"dueDate,omitempty"`
	Status      *string    `json:"status,omitempty"`
	AssignedTo  *string    `json:"assignedTo,omitempty"`
	DealID      *string    `json:"dealId,omitempty"`
}

type CreateTeamMemberInput struct {
	TeamMemberName    string  `json:"teamMemberName"`
	TeamMemberEmailID string  `json:"teamMemberEmailId"`
	Role              *string `json:"role,omitempty"`
}

type HealthStatus struct {
	Status    string  `json:"status"`
	Timestamp string  `json:"timestamp"`
	Env       *string `json:"env,omitempty"`
}

type InviteTeamMemberInput struct {
	TeamMemberName    string  `json:"teamMemberName"`
	TeamMemberEmailID string  `json:"teamMemberEmailId"`
	Role              *string `json:"role,omitempty"`
}

type JoinOrganisationInput struct {
	Token    string `json:"token"`
	Password string `json:"password"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Role     *string `json:"role,omitempty"`
}

type ResendInvitationInput struct {
	TeamMemberID string `json:"teamMemberId"`
}

type TokenInfo struct {
	Name             string `json:"name"`
	Email            string `json:"email"`
	OrganizationName string `json:"organizationName"`
	Role             string `json:"role"`
}

type UpdateContactInput struct {
	Name           string  `json:"name"`
	Email          *string `json:"email,omitempty"`
	Phone          *string `json:"phone,omitempty"`
	OrganisationID *string `json:"organisationId,omitempty"`
}

type UpdateDealInput struct {
	Name       string   `json:"name"`
	PropertyID *string  `json:"propertyId,omitempty"`
	AssignedTo *string  `json:"assignedTo,omitempty"`
	Status     *string  `json:"status,omitempty"`
	Value      *float64 `json:"value,omitempty"`
}

type UpdateOrganisationInput struct {
	OrganisationName string `json:"organisationName"`
}

type UpdatePropertyInput struct {
	Name    string  `json:"name"`
	Address *string `json:"address,omitempty"`
	OwnerID *string `json:"ownerId,omitempty"`
	Status  *string `json:"status,omitempty"`
}

type UpdateTaskInput struct {
	Title       string     `json:"title"`
	Description *string    `json:"description,omitempty"`
	DueDate     *time.Time `json:"dueDate,omitempty"`
	Status      *string    `json:"status,omitempty"`
	AssignedTo  *string    `json:"assignedTo,omitempty"`
	DealID      *string    `json:"dealId,omitempty"`
}

type UpdateTeamMemberInput struct {
	TeamMemberName    string `json:"teamMemberName"`
	TeamMemberEmailID string `json:"teamMemberEmailId"`
}
